### PR TITLE
Added sorting flags to listArtifacts and listRemotePaths

### PR DESCRIPTION
**Pull request by wandell**
It is possible we just always sort, rather than have the sort flag set.
It is annoying that one is sortFlag and the other is sortArtifacts.  Maybe they should both
be sortFlag, but then we don't know what we are sorting on for the artifact case.

### CODE REVIEW

**Comment by benjamin-heasly** [comment]
I think this is great!

I would like to extend this in a couple of ways:
- Push the sorting code into the plain-old functions like `rdtListRemotePaths()`, so that sorting is not limited to RdtClient.
- Change the name of the `sortArtifacts` parameter to `sortField` and let the user sort on other fields if they want -- "name", "type", and "version" seem potentially useful.  As in your comment, we could default to sorting and default field could be "artifactId".  If the user really wants to prevent sorting from happening, they could pass in a non-field-name like "none".
- Add the `sortField` parameter to `rdtSearchArtifacts()` and `rdtListLocalArtifacts()` as well.

I will make these changes and add them to this branch and PR and then see what you think.

**Comment by benjamin-heasly** [comment]
OK, I made the changes I described above.  How does this look to you now?

**Comment by wandell** [comment]
Will try to read soon - after I return from teaching class.  Thanks …

Brian

On Jan 12, 2016, at 1:09 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, I made the changes I described above. How does this look to you now?

—
Reply to this email directly or view it on GitHubhttps://github.com/isetbio/RemoteDataToolbox/pull/50#issuecomment-171055071.

---

Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by wandell** [comment]
It is my impression that the sorting happens within each path.  Is that right?  And is that the desired behavior?  My impression comes from running  rdt.listArtifacts while I am at the root level.  The artifacts seem to be sorted within each both but not globally.  

Maybe this is the right behavior.  Or maybe we really want a final, global sort on all of the artifacts.

**Comment by benjamin-heasly** [comment]
Oh, you're right.  I intended the sort to be global but I missed a final sort when RdtClient is at the root and iterates over all the remotePaths.

I added the final sort.

**Comment by wandell** [comment]
I downloaded and ran.  LGTM!

**Comment by wandell** [comment]
Deleting branch because they tell me it is best practice.  Frightens me each time.

**Comment by benjamin-heasly** [comment]
Cool.  Thanks!

I agree on both counts about deleting: best practice and frightening.

I think Git doesn't actually destroy information though, just makes the branch appear to go away.  Here is an SO about undeleting!
  http://stackoverflow.com/questions/3640764/can-i-recover-branch-after-its-deletion-in-git

**Pull request merged**
