### PR TITLE
File types

### PR DESCRIPTION
**Pull request by benjamin-heasly**
This PR is aimed at our discussion in https://github.com/isetbio/RemoteDataToolbox/issues/59.  

If review looks good, I think it's ready to merge.  All tests are passing on my end.

Main points:
- List, search, read, and publish functions now return consistent urls to artifact files (some had been returning shorter urls to artifact folders).
- You can specify a `destinationFolder` where read functions should copy fetched files.  These files will have sensible names like "foo.bar" or "foo.nii.gz", which might differ from names used internally by Gradle/Archiva/Maven.
- For unfamiliar file types read functions now return the file name as a string, instead raw file bytes as a char array. 
- You can specify a `loadFunction` to customize how read functions should load file data.
- Read functions can print verbose messages about what happened to fetched files.

### CODE REVIEW

**Comment by wandell** [comment]
I edited rdtBuilArtifactUrl because rd.openBrowser was missing the fileName argument.
I am testing the reading files from the Vistasoft repository.
I hope to finish this by tomorrow.

**Comment by wandell** [comment]
@benjamin-heasly 
Is it possible to store the name of the original file on upload into the artifact structure?  I think that could be helpful.  The reason is we can then always undo the name change that Gradle or Archiva impose when they store it.  Perhaps even the file name and the path where it came from?

I hope to finish other checking today.  I spent a little more time last night.

**Comment by benjamin-heasly** [comment]
@wandell Hi Brian,

Yes, I think we could store the file name.  We could add an "originalFileName" to the artifact pom-file along with existing metadata like "name" and "description".

This would add a degree of freedom:  a file name that is independent of the artifactId and the artifact type.  I am wondering if this DOF might cause confusion and facilitate mistakes.

To my thinking, it is a good thing to simplify and assume that the file name is always determined by the artifactId and type.

In the current PR code, when you supply a `destinationFolder`, the code should give you file names of the form `artifactId`.`type`.  Are you in a scenario where this is not what you need?

---

We could also store some path information in the pom.  What path are you thinking of?  I think the remotePath is already taken care of by the system.  And to my mind it is good to keep local paths local, and not put them on the server.  So I would like to learn more about the scenario where this would help.

**Comment by wandell** [comment]
@benjamin-heasly 

This was just my confusion, again.  I finally got some more time to work on this, and I can see that adding  the destinationFolder parameter/value did properly generate the file.  I tried it on one of those NIfTI/Gzip files.  Worked well.

If I am understanding correctly, you have the proper way of inverting the file name and this method is invoked when we set a destinationFolder.  

I am going to illustrate a few more cases in a script I am preparing for my MRI colleagues. Then I will accept the pull merge, and off we go.  I agree with your points that if this works, we should not add another variable because there will be an unnecessary DOF.

**Pull request merged**
